app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
   'auth' => 'Auth\AuthController',
   'password' => 'Auth\PasswordController',
]);

Route::resource('categories', 'BusinessList\CategoriesController', ['except' => ['show']]);
Route::resource('businesses', 'BusinessList\BusinessesController', ['except' => ['show']]);

Route::get('{slug}', 'WelcomeController@business');

app/Http/Controllers/BusinessList/BusinessesController.php
<?php namespace App\Http\Controllers\BusinessList;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

use App\Models\Category;
use App\Models\Business;
use Validator;

class BusinessesController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$Businesses = Business::all();
		return view('businesses.index', compact('Businesses'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$Categories = Category::all();
		return view('businesses.form', compact('Categories'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Request $request)
	{
		$validator = Validator::make($request->all(), $this->rules());

		if($validator->fails())
		{
			return redirect()->route('businesses.create')
						 ->withErrors($validator)
						 ->withInput();
		}

		$Business              = new Business;
		$Business->category_id = $request->get('category');
		$Business->name        = $request->get('name');
		$Business->description = $request->get('description');

		// Picture
		if ($request->hasFile('photo'))
		   {
				$image = $request->file('photo');
				$ext    = $image->getClientOriginalExtension();
				$image->move('static/images/businesses/', $Business->slug . '.' .$ext);

				$Business->photo_uri   = 'static/images/businesses/' . $Business->slug . '.' .$ext;
		   }
		else
			$Business->photo_uri = null;

		$Business->slug        = str_slug($request->get('name'));
		$Business->save();

		return redirect()->route('businesses.index');
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$Business   = Business::find($id);
		$Categories = Category::all();

		if ($Business)
			return view('businesses.form', compact('Business', 'Categories'));

		abort(404);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, Request $request)
	{
		$validator = Validator::make($request->all(), $this->rules());

		if($validator->fails())
		{
			return redirect()->route('businesses.edit', $id)
						 ->withErrors($validator)
						 ->withInput();
		}

		$Business              = Business::find($id);
		$Business->category_id = $request->get('category');
		$Business->name        = $request->get('name');
		$Business->description = $request->get('description');
		$Business->slug        = str_slug($request->get('name'));

		// Picture
		if ($request->hasFile('photo'))
		   {
				$image = $request->file('photo');
				$ext    = $image->getClientOriginalExtension();
				$image->move('static/images/businesses/', $Business->slug . '.' .$ext);

				$Business->photo_uri   = 'static/images/businesses/' . $Business->slug . '.' .$ext;
		   }

		$Business->save();

		return redirect()->route('businesses.index');

	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Business::find($id)->delete();
		return redirect()->route('businesses.index');
	}

	private function rules()
	{
		return [
			'description' => 'required',
			'name'        => 'required',
		];
	}
}

resources/views/businesses/form.blade.php
@extends('app')

@section('title', isset($Business) ? $Business->name : 'Create new Business')

@section('content')
@if (isset($Business))
<div class="modal fade" id="sureDelete" tabindex="-1" role="dialog" aria-labelledby="sureDeleteLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h5 class="modal-title" id="sureDeleteLabel">Delete Business?</h5>
      </div>
      <div class="modal-body">
        <p class="lead text-warning"> Are you sure to delete this? </p>
        <p class="">This process <strong>can't be undone.</strong></p>
      </div>
      <div class="modal-footer">

        <form action="{{ route('businesses.destroy', $Business->id) }}" method="POST">
	        <input type="hidden" name="_token" value="{{ csrf_token() }}">
	        <input type="hidden" name="_method" value="DELETE">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button type="submit" class="btn btn-danger">Yes, Delete</button>
        </form>

      </div>
    </div>
  </div>
</div>
@endif
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
          <p class="panel-title">Business</p>
        </div>

				<div class="panel-body">
					@if (count($errors) > 0)
						<div class="alert alert-danger">
							<strong>Whoops!</strong> There were some problems with your input.<br><br>
							<ul>
								@foreach ($errors->all() as $error)
									<li>{{ $error }}</li>
								@endforeach
							</ul>
						</div>
					@endif

				<form class="form-horizontal" role="form" method="POST" action="{{ isset($Business) ? route('businesses.update', $Business->id) : route('businesses.store') }}" enctype="multipart/form-data">
					<input type="hidden" name="_token" value="{{ csrf_token() }}">
               @if (isset($Business))
               <input type="hidden" name="_method" value="PUT">
               @endif

               <div class="form-group">
                  <label class="col-md-4 control-label">Category</label>
                  <div class="col-md-6">
                     <select name="category" class="form-control">
                        <option value="-1">Select a Category</option>
                        @foreach ($Categories as $Category)
                        <option value="{{ $Category->id }}" {{ old('category', isset($Business) ? $Business->category_id : '0') == $Category->id ? 'selected' : '' }}>{{ $Category->name }}</option>
                        @endforeach
                     </select>
                  </div>
               </div>

               <div class="form-group">
                  <label class="col-md-4 control-label">Name</label>
                  <div class="col-md-6">
                     <input type="text" name="name" class="form-control" value="{{ old('name', isset($Business) ? $Business->name : '') }}">
                  </div>
               </div>

					<div class="form-group">
						<label class="col-md-4 control-label">Description</label>
						<div class="col-md-6">
							<textarea name="description" class="form-control" rows="4">{{ old('description', isset($Business) ? $Business->description : '') }}</textarea>
						</div>
					</div>

          <div class="form-group">
            <label class="col-md-4 control-label">Picture</label>
            <div class="col-md-6">
              <input name="photo" value="Choose..." accept="image/*" type="file" class="form-control btn-xs">
            </div>
          </div>

					<div class="form-group">
						<div class="col-md-6 col-md-offset-4">
							<button type="submit" class="btn btn-primary">Save</button>
						</div>
					</div>
				</form>

        @if (isset($Business))
          @if ($Business->photo_uri)
          <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
            <div class="well well-sm">
              <img src="/{{ $Business->photo_uri }}" class="img-responsive">
            </div>
          </div>
          @endif
        @endif

				</div>

				@if (isset($Business))
				<div class="panel-footer text-right">
					<button class="btn btn-danger" data-toggle="modal" data-target="#sureDelete">Delete</button>
				</div>
				@endif
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/businesses/index.blade.php
@extends('app')
@section('title', 'All Businesses')
@section('content')
<div class="container">
   <div class="row">
      <div class="col-md-12">
         <div class="panel panel-default">
            <div class="panel-heading clearfix">
               <span class="panel-title">All Business</span>
               <span class="pull-right">
                  <a href="{{ route('businesses.create') }}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add</a>
               </span>
            </div>

            <div class="panel-body">

               <div class="row">

                  @foreach($Businesses as $Business)

                  <div class="col-sm-6 col-md-4">
                     <div class="panel panel-default">
                        <div class="panel-footer">
                           <p class="h2">{{$Business->name}}</p>
                           <p class="small">{{ $Business->description }}</p>
                           <p class="text-right">
                              @if ($Business->photo_uri)
                              <span class="lead pull-left text-muted">
                                 <span class="glyphicon glyphicon-picture"></span>
                              </span>
                              @endif
                              <a href="{{ route('businesses.edit', $Business->id) }}" class="btn btn-default">Edit</a>
                           </p>
                        </div>
                     </div>
                  </div>

                  @endforeach

               </div>

            </div>
         </div>
      </div>
   </div>
</div>
@endsection